name: Deploy

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.14

    - name: Compile
      run: mvn clean test-compile -B

    - name: Test
      run: mvn verify -B

    - name: Coverage
      run: mvn clean test jacoco:report coveralls:report

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        #platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: devsouza01/teste-ci-cd:latest
